//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class EgitimDetayFormuSoruBaslik : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual string Tanim
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Sira
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<EgitimDetayFormuSoru> EgitimDetayFormuSoru
        {
            get
            {
                if (_egitimDetayFormuSoru == null)
                {
                    var newCollection = new FixupCollection<EgitimDetayFormuSoru>();
                    newCollection.CollectionChanged += FixupEgitimDetayFormuSoru;
                    _egitimDetayFormuSoru = newCollection;
                }
                return _egitimDetayFormuSoru;
            }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuSoru, value))
                {
                    var previousValue = _egitimDetayFormuSoru as FixupCollection<EgitimDetayFormuSoru>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEgitimDetayFormuSoru;
                    }
                    _egitimDetayFormuSoru = value;
                    var newValue = value as FixupCollection<EgitimDetayFormuSoru>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEgitimDetayFormuSoru;
                    }
                }
            }
        }
        private ICollection<EgitimDetayFormuSoru> _egitimDetayFormuSoru;

        #endregion

        #region Association Fixup
    
        private void FixupEgitimDetayFormuSoru(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EgitimDetayFormuSoru item in e.NewItems)
                {
                    item.EgitimDetayFormuSoruBaslik = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EgitimDetayFormuSoru item in e.OldItems)
                {
                    if (ReferenceEquals(item.EgitimDetayFormuSoruBaslik, this))
                    {
                        item.EgitimDetayFormuSoruBaslik = null;
                    }
                }
            }
        }

        #endregion

    }
}
