//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class EgitimDetayFormuSoru : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> EgitimDetayFormuSoruBaslikId
        {
            get { return _egitimDetayFormuSoruBaslikId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_egitimDetayFormuSoruBaslikId != value)
                    {
                        if (EgitimDetayFormuSoruBaslik != null && EgitimDetayFormuSoruBaslik.Id != value)
                        {
                            EgitimDetayFormuSoruBaslik = null;
                        }
                        _egitimDetayFormuSoruBaslikId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _egitimDetayFormuSoruBaslikId;
    
        public virtual string Tanim
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CevapTuru
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Sira
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TxtSatirSayisi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual EgitimDetayFormuSoruBaslik EgitimDetayFormuSoruBaslik
        {
            get { return _egitimDetayFormuSoruBaslik; }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuSoruBaslik, value))
                {
                    var previousValue = _egitimDetayFormuSoruBaslik;
                    _egitimDetayFormuSoruBaslik = value;
                    FixupEgitimDetayFormuSoruBaslik(previousValue);
                }
            }
        }
        private EgitimDetayFormuSoruBaslik _egitimDetayFormuSoruBaslik;
    
        public virtual ICollection<EgitimDetayFormuSoruBaglanti> EgitimDetayFormuSoruBaglanti
        {
            get
            {
                if (_egitimDetayFormuSoruBaglanti == null)
                {
                    var newCollection = new FixupCollection<EgitimDetayFormuSoruBaglanti>();
                    newCollection.CollectionChanged += FixupEgitimDetayFormuSoruBaglanti;
                    _egitimDetayFormuSoruBaglanti = newCollection;
                }
                return _egitimDetayFormuSoruBaglanti;
            }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuSoruBaglanti, value))
                {
                    var previousValue = _egitimDetayFormuSoruBaglanti as FixupCollection<EgitimDetayFormuSoruBaglanti>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEgitimDetayFormuSoruBaglanti;
                    }
                    _egitimDetayFormuSoruBaglanti = value;
                    var newValue = value as FixupCollection<EgitimDetayFormuSoruBaglanti>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEgitimDetayFormuSoruBaglanti;
                    }
                }
            }
        }
        private ICollection<EgitimDetayFormuSoruBaglanti> _egitimDetayFormuSoruBaglanti;
    
        public virtual ICollection<EgitimDetayFormuSoruSecenekleri> EgitimDetayFormuSoruSecenekleri
        {
            get
            {
                if (_egitimDetayFormuSoruSecenekleri == null)
                {
                    var newCollection = new FixupCollection<EgitimDetayFormuSoruSecenekleri>();
                    newCollection.CollectionChanged += FixupEgitimDetayFormuSoruSecenekleri;
                    _egitimDetayFormuSoruSecenekleri = newCollection;
                }
                return _egitimDetayFormuSoruSecenekleri;
            }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuSoruSecenekleri, value))
                {
                    var previousValue = _egitimDetayFormuSoruSecenekleri as FixupCollection<EgitimDetayFormuSoruSecenekleri>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEgitimDetayFormuSoruSecenekleri;
                    }
                    _egitimDetayFormuSoruSecenekleri = value;
                    var newValue = value as FixupCollection<EgitimDetayFormuSoruSecenekleri>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEgitimDetayFormuSoruSecenekleri;
                    }
                }
            }
        }
        private ICollection<EgitimDetayFormuSoruSecenekleri> _egitimDetayFormuSoruSecenekleri;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupEgitimDetayFormuSoruBaslik(EgitimDetayFormuSoruBaslik previousValue)
        {
            if (previousValue != null && previousValue.EgitimDetayFormuSoru.Contains(this))
            {
                previousValue.EgitimDetayFormuSoru.Remove(this);
            }
    
            if (EgitimDetayFormuSoruBaslik != null)
            {
                if (!EgitimDetayFormuSoruBaslik.EgitimDetayFormuSoru.Contains(this))
                {
                    EgitimDetayFormuSoruBaslik.EgitimDetayFormuSoru.Add(this);
                }
                if (EgitimDetayFormuSoruBaslikId != EgitimDetayFormuSoruBaslik.Id)
                {
                    EgitimDetayFormuSoruBaslikId = EgitimDetayFormuSoruBaslik.Id;
                }
            }
            else if (!_settingFK)
            {
                EgitimDetayFormuSoruBaslikId = null;
            }
        }
    
        private void FixupEgitimDetayFormuSoruBaglanti(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EgitimDetayFormuSoruBaglanti item in e.NewItems)
                {
                    item.EgitimDetayFormuSoru = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EgitimDetayFormuSoruBaglanti item in e.OldItems)
                {
                    if (ReferenceEquals(item.EgitimDetayFormuSoru, this))
                    {
                        item.EgitimDetayFormuSoru = null;
                    }
                }
            }
        }
    
        private void FixupEgitimDetayFormuSoruSecenekleri(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EgitimDetayFormuSoruSecenekleri item in e.NewItems)
                {
                    item.EgitimDetayFormuSoru = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EgitimDetayFormuSoruSecenekleri item in e.OldItems)
                {
                    if (ReferenceEquals(item.EgitimDetayFormuSoru, this))
                    {
                        item.EgitimDetayFormuSoru = null;
                    }
                }
            }
        }

        #endregion

    }
}
