//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class EgitimDetayFormuSoruSecenekleri : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual string Tanim
        {
            get;
            set;
        }
    
        public virtual Nullable<int> EgitimDetayFormuSoruId
        {
            get { return _egitimDetayFormuSoruId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_egitimDetayFormuSoruId != value)
                    {
                        if (EgitimDetayFormuSoru != null && EgitimDetayFormuSoru.Id != value)
                        {
                            EgitimDetayFormuSoru = null;
                        }
                        _egitimDetayFormuSoruId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _egitimDetayFormuSoruId;
    
        public virtual Nullable<int> Sira
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual EgitimDetayFormuSoru EgitimDetayFormuSoru
        {
            get { return _egitimDetayFormuSoru; }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuSoru, value))
                {
                    var previousValue = _egitimDetayFormuSoru;
                    _egitimDetayFormuSoru = value;
                    FixupEgitimDetayFormuSoru(previousValue);
                }
            }
        }
        private EgitimDetayFormuSoru _egitimDetayFormuSoru;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupEgitimDetayFormuSoru(EgitimDetayFormuSoru previousValue)
        {
            if (previousValue != null && previousValue.EgitimDetayFormuSoruSecenekleri.Contains(this))
            {
                previousValue.EgitimDetayFormuSoruSecenekleri.Remove(this);
            }
    
            if (EgitimDetayFormuSoru != null)
            {
                if (!EgitimDetayFormuSoru.EgitimDetayFormuSoruSecenekleri.Contains(this))
                {
                    EgitimDetayFormuSoru.EgitimDetayFormuSoruSecenekleri.Add(this);
                }
                if (EgitimDetayFormuSoruId != EgitimDetayFormuSoru.Id)
                {
                    EgitimDetayFormuSoruId = EgitimDetayFormuSoru.Id;
                }
            }
            else if (!_settingFK)
            {
                EgitimDetayFormuSoruId = null;
            }
        }

        #endregion

    }
}
