//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class EgitimDetayFormuDetay : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> EgitimDetayFormuId
        {
            get { return _egitimDetayFormuId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_egitimDetayFormuId != value)
                    {
                        if (EgitimDetayFormu != null && EgitimDetayFormu.Id != value)
                        {
                            EgitimDetayFormu = null;
                        }
                        _egitimDetayFormuId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _egitimDetayFormuId;
    
        public virtual string Cevap
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> EgitimDetayFormuSoruBaglantiId
        {
            get { return _egitimDetayFormuSoruBaglantiId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_egitimDetayFormuSoruBaglantiId != value)
                    {
                        if (EgitimDetayFormuSoruBaglanti != null && EgitimDetayFormuSoruBaglanti.Id != value)
                        {
                            EgitimDetayFormuSoruBaglanti = null;
                        }
                        _egitimDetayFormuSoruBaglantiId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _egitimDetayFormuSoruBaglantiId;

        #endregion

        #region Navigation Properties
    
        public virtual EgitimDetayFormu EgitimDetayFormu
        {
            get { return _egitimDetayFormu; }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormu, value))
                {
                    var previousValue = _egitimDetayFormu;
                    _egitimDetayFormu = value;
                    FixupEgitimDetayFormu(previousValue);
                }
            }
        }
        private EgitimDetayFormu _egitimDetayFormu;
    
        public virtual EgitimDetayFormuSoruBaglanti EgitimDetayFormuSoruBaglanti
        {
            get { return _egitimDetayFormuSoruBaglanti; }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuSoruBaglanti, value))
                {
                    var previousValue = _egitimDetayFormuSoruBaglanti;
                    _egitimDetayFormuSoruBaglanti = value;
                    FixupEgitimDetayFormuSoruBaglanti(previousValue);
                }
            }
        }
        private EgitimDetayFormuSoruBaglanti _egitimDetayFormuSoruBaglanti;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupEgitimDetayFormu(EgitimDetayFormu previousValue)
        {
            if (previousValue != null && previousValue.EgitimDetayFormuDetay.Contains(this))
            {
                previousValue.EgitimDetayFormuDetay.Remove(this);
            }
    
            if (EgitimDetayFormu != null)
            {
                if (!EgitimDetayFormu.EgitimDetayFormuDetay.Contains(this))
                {
                    EgitimDetayFormu.EgitimDetayFormuDetay.Add(this);
                }
                if (EgitimDetayFormuId != EgitimDetayFormu.Id)
                {
                    EgitimDetayFormuId = EgitimDetayFormu.Id;
                }
            }
            else if (!_settingFK)
            {
                EgitimDetayFormuId = null;
            }
        }
    
        private void FixupEgitimDetayFormuSoruBaglanti(EgitimDetayFormuSoruBaglanti previousValue)
        {
            if (previousValue != null && previousValue.EgitimDetayFormuDetay.Contains(this))
            {
                previousValue.EgitimDetayFormuDetay.Remove(this);
            }
    
            if (EgitimDetayFormuSoruBaglanti != null)
            {
                if (!EgitimDetayFormuSoruBaglanti.EgitimDetayFormuDetay.Contains(this))
                {
                    EgitimDetayFormuSoruBaglanti.EgitimDetayFormuDetay.Add(this);
                }
                if (EgitimDetayFormuSoruBaglantiId != EgitimDetayFormuSoruBaglanti.Id)
                {
                    EgitimDetayFormuSoruBaglantiId = EgitimDetayFormuSoruBaglanti.Id;
                }
            }
            else if (!_settingFK)
            {
                EgitimDetayFormuSoruBaglantiId = null;
            }
        }

        #endregion

    }
}
