//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class EgitimDetayFormu : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Aktif
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> KapatmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> KapatanKullaniciId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AcmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> AcanKullaniciId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Tur
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenMerkez
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<EgitimDetayFormuDetay> EgitimDetayFormuDetay
        {
            get
            {
                if (_egitimDetayFormuDetay == null)
                {
                    var newCollection = new FixupCollection<EgitimDetayFormuDetay>();
                    newCollection.CollectionChanged += FixupEgitimDetayFormuDetay;
                    _egitimDetayFormuDetay = newCollection;
                }
                return _egitimDetayFormuDetay;
            }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuDetay, value))
                {
                    var previousValue = _egitimDetayFormuDetay as FixupCollection<EgitimDetayFormuDetay>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEgitimDetayFormuDetay;
                    }
                    _egitimDetayFormuDetay = value;
                    var newValue = value as FixupCollection<EgitimDetayFormuDetay>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEgitimDetayFormuDetay;
                    }
                }
            }
        }
        private ICollection<EgitimDetayFormuDetay> _egitimDetayFormuDetay;
    
        public virtual ICollection<EgitimDetayFormuGuncelleme> EgitimDetayFormuGuncelleme
        {
            get
            {
                if (_egitimDetayFormuGuncelleme == null)
                {
                    var newCollection = new FixupCollection<EgitimDetayFormuGuncelleme>();
                    newCollection.CollectionChanged += FixupEgitimDetayFormuGuncelleme;
                    _egitimDetayFormuGuncelleme = newCollection;
                }
                return _egitimDetayFormuGuncelleme;
            }
            set
            {
                if (!ReferenceEquals(_egitimDetayFormuGuncelleme, value))
                {
                    var previousValue = _egitimDetayFormuGuncelleme as FixupCollection<EgitimDetayFormuGuncelleme>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEgitimDetayFormuGuncelleme;
                    }
                    _egitimDetayFormuGuncelleme = value;
                    var newValue = value as FixupCollection<EgitimDetayFormuGuncelleme>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEgitimDetayFormuGuncelleme;
                    }
                }
            }
        }
        private ICollection<EgitimDetayFormuGuncelleme> _egitimDetayFormuGuncelleme;

        #endregion

        #region Association Fixup
    
        private void FixupEgitimDetayFormuDetay(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EgitimDetayFormuDetay item in e.NewItems)
                {
                    item.EgitimDetayFormu = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EgitimDetayFormuDetay item in e.OldItems)
                {
                    if (ReferenceEquals(item.EgitimDetayFormu, this))
                    {
                        item.EgitimDetayFormu = null;
                    }
                }
            }
        }
    
        private void FixupEgitimDetayFormuGuncelleme(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EgitimDetayFormuGuncelleme item in e.NewItems)
                {
                    item.EgitimDetayFormu = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EgitimDetayFormuGuncelleme item in e.OldItems)
                {
                    if (ReferenceEquals(item.EgitimDetayFormu, this))
                    {
                        item.EgitimDetayFormu = null;
                    }
                }
            }
        }

        #endregion

    }
}
