//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Seyehat
{
    using System;
    using System.Data.EntityClient;
    using System.Data.Objects;

    public partial class dbGoTripEntities : ObjectContext
    {
        public const string ConnectionString = "name=dbGoTripEntities";
        public const string ContainerName = "dbGoTripEntities";

        #region Constructors

        public dbGoTripEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }

        public dbGoTripEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }

        public dbGoTripEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }

        #endregion
        #region ObjectSet Properties

        public ObjectSet<tabloKurumsal> Islem_Kurumsal
        {
            get { return _islem_Kurumsal ?? (_islem_Kurumsal = CreateObjectSet<tabloKurumsal>("Islem_Kurumsal")); }
        }
        private ObjectSet<tabloKurumsal> _islem_Kurumsal;

        public ObjectSet<tblAyarlar> Islem_Ayarlar
        {
            get { return _islem_Ayarlar ?? (_islem_Ayarlar = CreateObjectSet<tblAyarlar>("Islem_Ayarlar")); }
        }
        private ObjectSet<tblAyarlar> _islem_Ayarlar;

        public ObjectSet<tblKullanici> Islem_Kullanici
        {
            get { return _islem_Kullanici ?? (_islem_Kullanici = CreateObjectSet<tblKullanici>("Islem_Kullanici")); }
        }
        private ObjectSet<tblKullanici> _islem_Kullanici;

        public ObjectSet<tblBlog> Tanim_Blog
        {
            get { return _tanim_Blog ?? (_tanim_Blog = CreateObjectSet<tblBlog>("Tanim_Blog")); }
        }
        private ObjectSet<tblBlog> _tanim_Blog;
        public ObjectSet<tblBlogKategori> Islem_BlogKategori
        {
            get { return _islem_BlogKategori ?? (_islem_BlogKategori = CreateObjectSet<tblBlogKategori>("Islem_BlogKategori")); }
        }
        private ObjectSet<tblBlogKategori> _islem_BlogKategori;
        public ObjectSet<tblGaleri> Tanim_Galeri
        {
            get { return _tanim_Galeri ?? (_tanim_Galeri = CreateObjectSet<tblGaleri>("Tanim_Galeri")); }
        }
        private ObjectSet<tblGaleri> _tanim_Galeri;

        public ObjectSet<tblGaleriKategori> Islem_GaleriKategori
        {
            get { return _islem_GaleriKategori ?? (_islem_GaleriKategori = CreateObjectSet<tblGaleriKategori>("Islem_GaleriKategori")); }
        }
        private ObjectSet<tblGaleriKategori> _islem_GaleriKategori;

        #endregion
    }
}
