//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Entity.Seyehat
{
    public partial class GoTripEntities : ObjectContext
    {
        public const string ConnectionString = "name=GoTripEntities";
        public const string ContainerName = "GoTripEntities";
    
        #region Constructors
    
        public GoTripEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public GoTripEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public GoTripEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<tabloKurumsal> tabloKurumsal
        {
            get { return _tabloKurumsal  ?? (_tabloKurumsal = CreateObjectSet<tabloKurumsal>("tabloKurumsal")); }
        }
        private ObjectSet<tabloKurumsal> _tabloKurumsal;
    
        public ObjectSet<tblAyarlar> tblAyarlar
        {
            get { return _tblAyarlar  ?? (_tblAyarlar = CreateObjectSet<tblAyarlar>("tblAyarlar")); }
        }
        private ObjectSet<tblAyarlar> _tblAyarlar;
    
        public ObjectSet<tblBlog> tblBlog
        {
            get { return _tblBlog  ?? (_tblBlog = CreateObjectSet<tblBlog>("tblBlog")); }
        }
        private ObjectSet<tblBlog> _tblBlog;
    
        public ObjectSet<tblBlogKategori> tblBlogKategori
        {
            get { return _tblBlogKategori  ?? (_tblBlogKategori = CreateObjectSet<tblBlogKategori>("tblBlogKategori")); }
        }
        private ObjectSet<tblBlogKategori> _tblBlogKategori;
    
        public ObjectSet<tblGaleri> tblGaleri
        {
            get { return _tblGaleri  ?? (_tblGaleri = CreateObjectSet<tblGaleri>("tblGaleri")); }
        }
        private ObjectSet<tblGaleri> _tblGaleri;
    
        public ObjectSet<tblGaleriKategori> tblGaleriKategori
        {
            get { return _tblGaleriKategori  ?? (_tblGaleriKategori = CreateObjectSet<tblGaleriKategori>("tblGaleriKategori")); }
        }
        private ObjectSet<tblGaleriKategori> _tblGaleriKategori;
    
        public ObjectSet<tblKullanici> tblKullanici
        {
            get { return _tblKullanici  ?? (_tblKullanici = CreateObjectSet<tblKullanici>("tblKullanici")); }
        }
        private ObjectSet<tblKullanici> _tblKullanici;
    
        public ObjectSet<tblTurPaket> tblTurPaket
        {
            get { return _tblTurPaket  ?? (_tblTurPaket = CreateObjectSet<tblTurPaket>("tblTurPaket")); }
        }
        private ObjectSet<tblTurPaket> _tblTurPaket;
    
        public ObjectSet<EgitimDetayFormuSoruBaslik> EgitimDetayFormuSoruBaslik
        {
            get { return _egitimDetayFormuSoruBaslik  ?? (_egitimDetayFormuSoruBaslik = CreateObjectSet<EgitimDetayFormuSoruBaslik>("EgitimDetayFormuSoruBaslik")); }
        }
        private ObjectSet<EgitimDetayFormuSoruBaslik> _egitimDetayFormuSoruBaslik;
    
        public ObjectSet<EgitimDetayFormuSoru> EgitimDetayFormuSoru
        {
            get { return _egitimDetayFormuSoru  ?? (_egitimDetayFormuSoru = CreateObjectSet<EgitimDetayFormuSoru>("EgitimDetayFormuSoru")); }
        }
        private ObjectSet<EgitimDetayFormuSoru> _egitimDetayFormuSoru;
    
        public ObjectSet<EgitimDetayFormu> EgitimDetayFormu
        {
            get { return _egitimDetayFormu  ?? (_egitimDetayFormu = CreateObjectSet<EgitimDetayFormu>("EgitimDetayFormu")); }
        }
        private ObjectSet<EgitimDetayFormu> _egitimDetayFormu;
    
        public ObjectSet<EgitimDetayFormuDetay> EgitimDetayFormuDetay
        {
            get { return _egitimDetayFormuDetay  ?? (_egitimDetayFormuDetay = CreateObjectSet<EgitimDetayFormuDetay>("EgitimDetayFormuDetay")); }
        }
        private ObjectSet<EgitimDetayFormuDetay> _egitimDetayFormuDetay;
    
        public ObjectSet<EgitimDetayFormuSoruBaglanti> EgitimDetayFormuSoruBaglanti
        {
            get { return _egitimDetayFormuSoruBaglanti  ?? (_egitimDetayFormuSoruBaglanti = CreateObjectSet<EgitimDetayFormuSoruBaglanti>("EgitimDetayFormuSoruBaglanti")); }
        }
        private ObjectSet<EgitimDetayFormuSoruBaglanti> _egitimDetayFormuSoruBaglanti;
    
        public ObjectSet<EgitimDetayFormuSoruSecenekleri> EgitimDetayFormuSoruSecenekleri
        {
            get { return _egitimDetayFormuSoruSecenekleri  ?? (_egitimDetayFormuSoruSecenekleri = CreateObjectSet<EgitimDetayFormuSoruSecenekleri>("EgitimDetayFormuSoruSecenekleri")); }
        }
        private ObjectSet<EgitimDetayFormuSoruSecenekleri> _egitimDetayFormuSoruSecenekleri;
    
        public ObjectSet<EgitimTuru> EgitimTuru
        {
            get { return _egitimTuru  ?? (_egitimTuru = CreateObjectSet<EgitimTuru>("EgitimTuru")); }
        }
        private ObjectSet<EgitimTuru> _egitimTuru;
    
        public ObjectSet<VeriKaynagi> VeriKaynagi
        {
            get { return _veriKaynagi  ?? (_veriKaynagi = CreateObjectSet<VeriKaynagi>("VeriKaynagi")); }
        }
        private ObjectSet<VeriKaynagi> _veriKaynagi;
    
        public ObjectSet<EgitimDetayFormuGuncelleme> EgitimDetayFormuGuncelleme
        {
            get { return _egitimDetayFormuGuncelleme  ?? (_egitimDetayFormuGuncelleme = CreateObjectSet<EgitimDetayFormuGuncelleme>("EgitimDetayFormuGuncelleme")); }
        }
        private ObjectSet<EgitimDetayFormuGuncelleme> _egitimDetayFormuGuncelleme;

        #endregion

    }
}
