//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Entity.Seyehat
{
    public partial class GoTripEntities : ObjectContext
    {
        public const string ConnectionString = "name=GoTripEntities";
        public const string ContainerName = "GoTripEntities";
    
        #region Constructors
    
        public GoTripEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public GoTripEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public GoTripEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<tabloKurumsal> tabloKurumsal
        {
            get { return _tabloKurumsal  ?? (_tabloKurumsal = CreateObjectSet<tabloKurumsal>("tabloKurumsal")); }
        }
        private ObjectSet<tabloKurumsal> _tabloKurumsal;
    
        public ObjectSet<tblAyarlar> tblAyarlar
        {
            get { return _tblAyarlar  ?? (_tblAyarlar = CreateObjectSet<tblAyarlar>("tblAyarlar")); }
        }
        private ObjectSet<tblAyarlar> _tblAyarlar;
    
        public ObjectSet<tblBlog> tblBlog
        {
            get { return _tblBlog  ?? (_tblBlog = CreateObjectSet<tblBlog>("tblBlog")); }
        }
        private ObjectSet<tblBlog> _tblBlog;
    
        public ObjectSet<tblBlogKategori> tblBlogKategori
        {
            get { return _tblBlogKategori  ?? (_tblBlogKategori = CreateObjectSet<tblBlogKategori>("tblBlogKategori")); }
        }
        private ObjectSet<tblBlogKategori> _tblBlogKategori;
    
        public ObjectSet<tblGaleri> tblGaleri
        {
            get { return _tblGaleri  ?? (_tblGaleri = CreateObjectSet<tblGaleri>("tblGaleri")); }
        }
        private ObjectSet<tblGaleri> _tblGaleri;
    
        public ObjectSet<tblGaleriKategori> tblGaleriKategori
        {
            get { return _tblGaleriKategori  ?? (_tblGaleriKategori = CreateObjectSet<tblGaleriKategori>("tblGaleriKategori")); }
        }
        private ObjectSet<tblGaleriKategori> _tblGaleriKategori;
    
        public ObjectSet<tblKullanici> tblKullanici
        {
            get { return _tblKullanici  ?? (_tblKullanici = CreateObjectSet<tblKullanici>("tblKullanici")); }
        }
        private ObjectSet<tblKullanici> _tblKullanici;
    
        public ObjectSet<tblTurPaket> tblTurPaket
        {
            get { return _tblTurPaket  ?? (_tblTurPaket = CreateObjectSet<tblTurPaket>("tblTurPaket")); }
        }
        private ObjectSet<tblTurPaket> _tblTurPaket;

        #endregion

    }
}
