//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class tblBlogKategori : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual string Ad
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tblBlog> tblBlog
        {
            get
            {
                if (_tblBlog == null)
                {
                    var newCollection = new FixupCollection<tblBlog>();
                    newCollection.CollectionChanged += FixuptblBlog;
                    _tblBlog = newCollection;
                }
                return _tblBlog;
            }
            set
            {
                if (!ReferenceEquals(_tblBlog, value))
                {
                    var previousValue = _tblBlog as FixupCollection<tblBlog>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixuptblBlog;
                    }
                    _tblBlog = value;
                    var newValue = value as FixupCollection<tblBlog>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixuptblBlog;
                    }
                }
            }
        }
        private ICollection<tblBlog> _tblBlog;

        #endregion

        #region Association Fixup
    
        private void FixuptblBlog(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tblBlog item in e.NewItems)
                {
                    item.tblBlogKategori = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tblBlog item in e.OldItems)
                {
                    if (ReferenceEquals(item.tblBlogKategori, this))
                    {
                        item.tblBlogKategori = null;
                    }
                }
            }
        }

        #endregion

    }
}
