//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Seyehat
{
    using Entity.Common;
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlogKategori : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBlogKategori()
        {
            this.tblBlog = new HashSet<tblBlog>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<int> OlusturanKullanici { get; set; }
        public Nullable<System.DateTime> OlusturulmaTarihi { get; set; }
        public Nullable<int> GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> GuncellestirilmeTarihi { get; set; }
        public bool Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBlog> tblBlog { get; set; }
    }
}
