//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entity.Seyehat
{
	using Common;

    public partial class tblGaleriKategori : IEntity
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public virtual string Adi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OlusturanKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OlusturulmaTarihi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuncelleyenKullanici
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GuncellestirilmeTarihi
        {
            get;
            set;
        }
    
        public virtual bool Silindi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tblGaleri> tblGaleri
        {
            get
            {
                if (_tblGaleri == null)
                {
                    var newCollection = new FixupCollection<tblGaleri>();
                    newCollection.CollectionChanged += FixuptblGaleri;
                    _tblGaleri = newCollection;
                }
                return _tblGaleri;
            }
            set
            {
                if (!ReferenceEquals(_tblGaleri, value))
                {
                    var previousValue = _tblGaleri as FixupCollection<tblGaleri>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixuptblGaleri;
                    }
                    _tblGaleri = value;
                    var newValue = value as FixupCollection<tblGaleri>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixuptblGaleri;
                    }
                }
            }
        }
        private ICollection<tblGaleri> _tblGaleri;

        #endregion

        #region Association Fixup
    
        private void FixuptblGaleri(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tblGaleri item in e.NewItems)
                {
                    item.tblGaleriKategori = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tblGaleri item in e.OldItems)
                {
                    if (ReferenceEquals(item.tblGaleriKategori, this))
                    {
                        item.tblGaleriKategori = null;
                    }
                }
            }
        }

        #endregion

    }
}
