//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.Seyehat
{
    using Entity.Common;
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici: IEntity
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string EMail { get; set; }
        public Nullable<int> OlusturanKullanici { get; set; }
        public Nullable<System.DateTime> OlusturulmaTarihi { get; set; }
        public Nullable<int> GuncelleyenKullanici { get; set; }
        public Nullable<System.DateTime> GuncellestirilmeTarihi { get; set; }
        public bool Silindi { get; set; }
        public int Id { get; set; }
    }
}
